sudo: required

language: bash
services: docker

env:
  - DOCKER_IMAGE=nginx-rtmp-ffmpeg

script:
  - docker build -t ${DOCKER_IMAGE} .

after_script:
  - docker images
  - docker run -d -p 1935:1935 -t ${DOCKER_IMAGE}
  - docker ps -a
